version: '3' 

services:
  app:
    build:
      context: ../ 
      dockerfile: sample/Dockerfile 
    ports:
      - "3000:3000" 
    env_file:
      - .env 
  func:
    build:
      context: ../ 
      dockerfile: sample/docker/azure-functions/Dockerfile
    ports:
      - "8080:80" 
    env_file:
      - .env